title: Tjango's Blog
author: Tjango
email: wolfgang.tjango@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog of a software dev, who likes to automate trivial stuff in life and somewhat obsess with dark theme.
  This "blog" actually serves as a record for myself, but I believe others could benefit from it as well.

show_excerpts: true

theme: minima

plugins:
  - jekyll-redirect-from


whitelist:
  - jekyll-redirect-from

